### ISSUE TITLE
Using Monopack

### ISSUE THREAD

**Issue by bradstewart** [flegall/monopack#70]
Great work so far! The `build` command is working as expected. I'm starting to integrate it with one of our projects, and have a few questions around your expected monopack usage:

* Can you prevent the final `yarn install` after a package is built?
  * Use case: CI server executes `monopack build`, compiled artifact is stored, and `yarn install` is run on a live system during deployment.
* One `monopack.config.js` in the root directory, or one per package/application?
  * My initial reaction is to use one config per application which builds into a relative `dist` directory.
* Any thoughts on adding additional files to the monopack-built package (e.g. `.env`, `Dockerfile`,etc)?
  * `CopyWebpackPlugin` seems to work, but this wouldn't work well with a single root `monopack.config`. Any consequences this of I'm not thinking about?
  * Doesn't necessarily have to be done by monopack, easy to add in another script.

**Comment by flegall** [comment]
Thanks for testing and thanks for the suggestions !

1. preventing yarn install is something I had in mind, it can be solved by adding a cli option or a config file option.
1. I'm planning on enabling multiple config files that can inherit from the top one, this way you can declare you babel/webpack configuration on top and your local options (output directory, extra dependencies etc..) in your bundle. Perhaps also the CLI could have an option to select its config file it there are multiple ones.
1. We could add a postBuild() function (or array of functions) in the config file that just does post-build actions (this function would take the output directory and the generated dependencies as parameters) 
    * I agree generating a Dockerfile does not necessarily belong to monopack, perhaps we could provide a post-build implementation as a dependency that does that :)

I'll create a few issues for this.

**Comment by bradstewart** [comment]
I like it. A postBuild() hook is a great idea--simple, generic.

**Comment by bradstewart** [comment]
Closing this in favor of the more specific issues you created. Thanks!
